name: Continuous Integration
on: [push]
branches:
  - 'main'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: docker build --tag veerapadala/cdrepo2 .

    - name: Login to Docker
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

    - name: login & push image to docker
      run: docker push veerapadala/cdrepo2